# -*- coding: utf-8 -*-
"""ai_video_pipeline_colab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JjYEE6H-V4RVXl77Y49R2GGYad2V0cIV
"""

!apt update -y
!apt install ffmpeg -y
!pip install -q openai-whisper

import os
import subprocess
import whisper
import json
import re

from google.colab import drive
drive.mount('/content/drive')

INPUT_VIDEO = "/content/drive/MyDrive/AI_VIDEO_PIPELINE/input/raw_video.mp4"
OUTPUT_DIR = "/content/drive/MyDrive/AI_VIDEO_PIPELINE/output/"
TEMP_DIR = "/content/temp"

os.makedirs(TEMP_DIR, exist_ok=True)

def transcribe_audio(video_path):
    audio_path = f"{TEMP_DIR}/audio.wav"

    subprocess.run(f'ffmpeg -i "{video_path}" -ar 16000 -ac 1 "{audio_path}" -y', shell=True)

    model = whisper.load_model("base")
    result = model.transcribe(audio_path)

    return result

def smart_trim(video_path, segments):
    merged = []
    threshold = 1.0

    current_start = segments[0]["start"]
    current_end = segments[0]["end"]

    for seg in segments[1:]:
        if seg["start"] - current_end <= threshold:
            current_end = seg["end"]
        else:
            merged.append((current_start, current_end))
            current_start = seg["start"]
            current_end = seg["end"]

    merged.append((current_start, current_end))

    clip_paths = []

    for i, (start, end) in enumerate(merged):
        clip = f"{TEMP_DIR}/clip_{i}.mp4"

        subprocess.run(
            f'ffmpeg -i "{video_path}" -ss {start} -to {end} -c:v libx264 -c:a aac "{clip}" -y',
            shell=True
        )

        clip_paths.append(clip)

    list_file = f"{TEMP_DIR}/list.txt"
    with open(list_file, "w") as f:
        for c in clip_paths:
            f.write(f"file '{c}'\n")

    output = f"{TEMP_DIR}/audio_enhanced.mp4"

    subprocess.run(
        f'ffmpeg -f concat -safe 0 -i "{list_file}" -c copy "{output}" -y',
        shell=True
    )

    return output

def remove_silence(video_path):
    output = f"{TEMP_DIR}/audio_enhanced.mp4"

    subprocess.run(
        f'ffmpeg -i "{video_path}" -af silenceremove=stop_periods=-1:stop_duration=1:stop_threshold=-40dB "{output}" -y',
        shell=True
    )

    return output

def format_time(seconds):
    hrs = int(seconds // 3600)
    mins = int((seconds % 3600) // 60)
    secs = int(seconds % 60)
    millis = int((seconds - int(seconds)) * 1000)
    return f"{hrs:02}:{mins:02}:{secs:02},{millis:03}"

def generate_srt(segments):
    srt_path = f"{OUTPUT_DIR}/subtitles.srt"

    srt_content = ""

    for i, seg in enumerate(segments, 1):
        start = format_time(seg["start"])
        end = format_time(seg["end"])
        text = seg["text"].strip()

        srt_content += f"{i}\n{start} --> {end}\n{text}\n\n"

    with open(srt_path, "w") as f:
        f.write(srt_content)

    return srt_path

def add_subtitles(video_path, srt_path):
    output = f"{TEMP_DIR}/audio_enhanced.mp4"

    subprocess.run(
        f'ffmpeg -i "{video_path}" -vf subtitles="{srt_path}" -c:a copy "{output}" -y',
        shell=True
    )

    return output

def style_subtitles(video_path, srt_path):
    output = f"{TEMP_DIR}/audio_enhanced.mp4"

    subprocess.run(
        f'''ffmpeg -i "{video_path}" -vf "subtitles={srt_path}:force_style='Fontsize=24,PrimaryColour=&Hffffff&,OutlineColour=&H000000&,BorderStyle=3'" -c:a copy "{output}" -y''',
        shell=True
    )

    return output

def extract_thumbnail(video_path):
    thumbnail_path = f"{OUTPUT_DIR}/thumbnail.jpg"

    duration = get_duration(video_path)
    timestamp = duration / 2

    subprocess.run(
        f'ffmpeg -ss {timestamp} -i "{video_path}" -vframes 1 "{thumbnail_path}" -y',
        shell=True
    )

    return thumbnail_path

def enhance_audio(video_path):
    output = f"{TEMP_DIR}/audio_enhanced.mp4"

    subprocess.run(
        f'ffmpeg -i "{video_path}" -af "afftdn,loudnorm" -c:v copy "{output}" -y',
        shell=True
    )

    return output

def color_correction(video_path):
    output = f"{TEMP_DIR}/audio_enhanced.mp4"

    subprocess.run(
        f'''ffmpeg -i "{video_path}" -vf "eq=contrast=1.2:brightness=0.05:saturation=1.3" -c:a copy "{output}" -y''',
        shell=True
    )

    return output

import subprocess

def get_duration(video_path):
    result = subprocess.run(
        f'ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 "{video_path}"',
        shell=True,
        capture_output=True,
        text=True
    )
    return float(result.stdout.strip())

def generate_report(input_video, final_video, features_used):
    report_path = f"{OUTPUT_DIR}/processing_report.txt"

    original_duration = get_duration(input_video)
    final_duration = get_duration(final_video)

    report = f"""
Video Processing Report
-----------------------

Original Duration: {round(original_duration,2)} sec
Final Duration: {round(final_duration,2)} sec

Features Applied:
"""

    for f in features_used:
        report += f"- {f}\n"

    report += f"\nOutput File:\n{final_video}\n"

    with open(report_path, "w") as f:
        f.write(report)

    print("Report generated at:", report_path)

def process_video(features):
    video = INPUT_VIDEO
    result = None
    applied_features = []

    if 1 in features or 3 in features or 5 in features:
        result = transcribe_audio(video)

    if 1 in features:
        video = smart_trim(video, result["segments"])
        applied_features.append("Smart Trim")

    if 2 in features:
        video = remove_silence(video)
        applied_features.append("Silence Removal")

    if 4 in features:
        video = enhance_audio(video)
        applied_features.append("Audio Enhancement")

    if 6 in features:
        video = color_correction(video)
        applied_features.append("Color Correction")

    if 3 in features:
        srt = generate_srt(result["segments"])
        video = add_subtitles(video, srt)
        applied_features.append("Subtitles")

    if 5 in features:
        if 3 not in features:
            srt = generate_srt(result["segments"])
        video = style_subtitles(video, srt)
        applied_features.append("Styled Subtitles")


    final_output = f"{OUTPUT_DIR}/final_video.mp4"

    subprocess.run(
        f'ffmpeg -i "{video}" -c copy "{final_output}" -y',
        shell=True
    )


    generate_report(INPUT_VIDEO, final_output, applied_features)

    return final_output

print("""
Select features:
1. Smart Trim (AI)
2. Silence Removal
3. Add Subtitles
4. Enhance Audio
5. Styled Subtitles
6. Color Correction
7. Extract Thumbnail
""")

user_input = input("Enter choices (e.g. 1,3,4): ")
features = list(map(int, user_input.split(",")))

final_video = process_video(features)

print("Final video saved at:", final_video)


final_output = f"{OUTPUT_DIR}/final_video.mp4"


if 7 in features:
    extract_thumbnail(final_output)


generate_report(INPUT_VIDEO, final_output, applied_features)

import shutil

shutil.rmtree(TEMP_DIR)
os.makedirs(TEMP_DIR, exist_ok=True)









